name: First Pipeline

on:
  push:
    branches: [main]

jobs:
  hello-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
       
      - name: show Node version
        run: node --version

      - name: show files
        run: ls -la
        
      - name: Run Fake Tests
        run: |
          echo "Running Test..."
          echo "Test1 passed"
          echo "Test2 passed"
          echo "All tests passed"

      - name: Build Project
        run: |
          mkdir build
          echo "Application Build Success" > build/app.txt
        
      - name: show build artifact
        run: ls -la build

      - name: Broken Step
        run: |
          echo "Start Debbuging"
          exit 1

      - name: print message
        run: echo "Hello from GitHub Actions"

       
